### ISSUE TITLE
Can't run docker container

### ISSUE THREAD

**Issue by Elchi3** [mdn/kumascript#666]
I meant to provide reviews for some PRs, but I can't get KumaScript up and running locally. My container fails to start with the error below. I tried removing the container and rebuilding it, but had no luck either. Any advice appreciated.

```
kumascript_1     | ## There is an issue with `node-fibers` ##
kumascript_1     | `/app/node_modules/fibers/bin/linux-x64-57/fibers.node` is missing.
kumascript_1     | 
kumascript_1     | Try running this to fix the issue: /usr/local/bin/node /app/node_modules/fibers/build
kumascript_1     | /app/node_modules/fibers/fibers.js:20
kumascript_1     | 	throw new Error('Missing binary. See message above.');
kumascript_1     | 	^
kumascript_1     | 
kumascript_1     | Error: Missing binary. See message above.
kumascript_1     |     at Object.<anonymous> (/app/node_modules/fibers/fibers.js:20:8)
kumascript_1     |     at Module._compile (module.js:652:30)
kumascript_1     |     at Object.Module._extensions..js (module.js:663:10)
kumascript_1     |     at Module.load (module.js:565:32)
kumascript_1     |     at tryModuleLoad (module.js:505:12)
kumascript_1     |     at Function.Module._load (module.js:497:3)
kumascript_1     |     at Module.require (module.js:596:17)
kumascript_1     |     at require (internal/module.js:11:18)
kumascript_1     |     at Object.<anonymous> (/app/lib/kumascript/templates.js:11:13)
kumascript_1     |     at Module._compile (module.js:652:30)
```

**Comment by Elchi3** [comment]
Thanks @jwhitlock! 

![Like a boss](https://media2.giphy.com/media/MzId7vT7YOUzm/giphy.gif)

**Comment by jwhitlock** [comment]
If you run across a way to avoid this problem in the future, please let me know.
