### ISSUE TITLE
Problem executing template APIRef

### ISSUE THREAD

**Issue by ExE-Boss** [mdn/kumascript#791]
```
Problem executing template APIRef:
    1 | <div>{{ APIRef("HTML DOM") }}</div>
-------------^
    2 | 

TypeError: ejs:1
 >> 1| <%
    2| // API Sidebar
    3| //
    4| // Parameters:

Cannot read property 'indexOf' of undefined
    at getImplementedBy (eval at compile (/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:124:52)
    at eval (eval at compile (/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:130:1)
    at returnedFn (/node_modules/ejs/lib/ejs.js:580:17)
    at /app/lib/kumascript/templates.js:71:26
```

This issue has been encountered on every page that uses [the `APIRef` macro](https://github.com/mdn/kumascript/blob/master/macros/APIRef.ejs).

Diff between previous and current deployment: https://github.com/mdn/kumascript/compare/1f3b66a6d9e6783b15e38c1852365aad52d87d97...75ea74a9ec19272a6b635dc8c749ca25df2fce00

**Comment by Elchi3** [comment]
Thanks! Looking at this (while having my first coffee).

**Comment by jwhitlock** [comment]
Cross-filed as [bug 1487640](https://bugzilla.mozilla.org/show_bug.cgi?id=1487640)
