### ISSUE TITLE
Problem executing template `bug`

### ISSUE THREAD

**Issue by ExE-Boss** [mdn/kumascript#800]
First stack trace from https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/53:
```
    Problem executing template bug:
       57 |  <li>The {{domxref("CompositionEvent.CompositionEvent", "CompositionEvent")}} constructor has been implemented (see {{bug(1002256)}}).</li>
       58 |  <li>The {{domxref("MouseEvent.x")}} and {{domxref("MouseEvent.y")}} aliases of {{domxref("MouseEvent.clientX")}}/{{domxref("MouseEvent.clientY")}} have been implemented (see {{bug(424390)}}).</li>
       59 |  <li>The {{Event("auxclick")}} event and corresponding {{domxref("GlobalEventHandlers.onauxclick")}} handler have been implemented (see {{bug(1304044)}}).</li>
    ------------------------------------------------------------------------------------------------------------------------------------------------^
       60 |  <li>The {{Event("transitioncancel")}} event is now fired after a <a href="/en-US/docs/Web/CSS/CSS_Transitions">transition</a> is cancelled. See {{domxref("GlobalEventHandlers.ontransitioncancel")}} for more details and an example ({{bug("1264125")}}).</li>
       61 | </ul>

    SyntaxError: ejs:1
     >> 1| <%
        2| /*
        3|  * Inserts a link to a bug in Mozilla's Bugzilla database.
        4|  *

    Unexpected token T in JSON at position 0
        at JSON.parse (<anonymous>)
        at Object.fetchJSONResource (eval at compile (/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:292:21)
        at eval (eval at compile (/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:38:26)
        at returnedFn (/node_modules/ejs/lib/ejs.js:580:17)
        at /app/lib/kumascript/templates.js:71:26
```

**Comment by ExE-Boss** [comment]
Duplicate of #751
